"""initial

Revision ID: a2f2f2dff908
Revises:
Create Date: 2025-11-17 02:28:09.926551

"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = "a2f2f2dff908"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "game_embeddings",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("game_id", sa.String(), nullable=False),
        sa.Column("dimension", sa.Integer(), nullable=False),
        sa.Column("title_embedding", sa.LargeBinary(), nullable=False),
        sa.Column("description_embedding", sa.LargeBinary(), nullable=False),
        sa.Column("metadata", sqlite.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("game_id"),
    )
    with op.batch_alter_table("game_embeddings", schema=None) as batch_op:
        batch_op.create_index("idx_game_embeddings_dimension", ["dimension"], unique=False)
        batch_op.create_index("idx_game_embeddings_game_id", ["game_id"], unique=False)

    op.create_table(
        "game_tags",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column("label", sa.String(), nullable=False),
        sa.Column("tag_class", sa.String(), nullable=False),
        sa.Column("igdb_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("igdb_id", "tag_class", name="uq_game_tags_igdb_id_class"),
        sa.UniqueConstraint("slug", "tag_class", name="uq_game_tags_slug_class"),
    )
    with op.batch_alter_table("game_tags", schema=None) as batch_op:
        batch_op.create_index("idx_game_tags_igdb_id", ["igdb_id"], unique=False)
        batch_op.create_index("idx_game_tags_tag_class", ["tag_class"], unique=False)

    op.create_table(
        "igdb_games",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("igdb_id", sa.Integer(), nullable=False),
        sa.Column("slug", sa.String(), nullable=True),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("tags_cache", sa.Text(), server_default=sa.text("('')"), nullable=False),
        sa.Column("release_date", sa.String(), nullable=True),
        sa.Column("cover_url", sa.String(), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("checksum", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("igdb_id"),
        sa.UniqueConstraint("slug"),
    )
    with op.batch_alter_table("igdb_games", schema=None) as batch_op:
        batch_op.create_index("idx_igdb_games_release", ["release_date"], unique=False)

    op.create_table(
        "game_tag_links",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("game_id", sa.Integer(), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["game_id"], ["igdb_games.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tag_id"], ["game_tags.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("game_id", "tag_id"),
    )
    with op.batch_alter_table("game_tag_links", schema=None) as batch_op:
        batch_op.create_index("idx_game_tag_links_game_id", ["game_id"], unique=False)

    op.create_table(
        "user_favorite_games",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("game_id", sa.Integer(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "added_at", sa.DateTime(), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.ForeignKeyConstraint(["game_id"], ["igdb_games.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("game_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_favorite_games")
    with op.batch_alter_table("game_tag_links", schema=None) as batch_op:
        batch_op.drop_index("idx_game_tag_links_game_id")

    op.drop_table("game_tag_links")
    with op.batch_alter_table("igdb_games", schema=None) as batch_op:
        batch_op.drop_index("idx_igdb_games_release")

    op.drop_table("igdb_games")
    with op.batch_alter_table("game_tags", schema=None) as batch_op:
        batch_op.drop_index("idx_game_tags_tag_class")
        batch_op.drop_index("idx_game_tags_igdb_id")

    op.drop_table("game_tags")
    with op.batch_alter_table("game_embeddings", schema=None) as batch_op:
        batch_op.drop_index("idx_game_embeddings_game_id")
        batch_op.drop_index("idx_game_embeddings_dimension")

    op.drop_table("game_embeddings")
    # ### end Alembic commands ###
